Models/ActivoFijo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace activos.Models
{
    public class ActivoFijo
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id_activo_fijo { get; set; }

        [Required]
        [StringLength(100)]
        public string? Descripcion { get; set; }

        // Propiedad de navegación para el departamento
        [ForeignKey("Departamento")]
        public int Id_departamento { get; set; }
        public Departamento? Departamento { get; set; }

        // Propiedad de navegación para el tipo de activo
        [ForeignKey("TipoActivo")]
        public int Id_tipo_activo { get; set; }
        public TipoActivo? TipoActivo { get; set; }

        [DataType(DataType.Date)]
        public DateTime FechaRegistro { get; set; }

        [Required(ErrorMessage = "El campo Valor de compra es obligatorio.")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "El campo Valor de Compra solo puede contener números y un punto decimal opcional, con hasta 2 decimales.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "El campo Valor de compra debe ser mayor que cero.")]
        [Column(TypeName = "decimal(18, 2)")]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]
        public decimal ValorCompra { get; set; }

        [Required(ErrorMessage = "El campo Depreciación acumulada es obligatorio.")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "El campo Depreciación acumulada solo puede contener números y un punto decimal opcional, con hasta 2 decimales.")]
        [Range(0, double.MaxValue, ErrorMessage = "El campo Depreciación acumulada debe ser mayor o igual a cero.")]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal DepreciacionAcumulada { get; set; }

        public bool Estado { get; set; }
    }
}

Controllers/ActivoFijosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using activos.Models;

namespace activos.Controllers
{
    public class ActivoFijosController : Controller
    {
        private readonly MyDbContext _context;

        public ActivoFijosController(MyDbContext context)
        {
            _context = context;
        }

        // GET: ActivoFijos
        public async Task<IActionResult> Index( string buscar_Activo)
        {
            var Activos = from ActivoFijo in _context.ActivosFijos select ActivoFijo;
            if (!String.IsNullOrEmpty(buscar_Activo))
            {
                Activos = Activos.Where(s => s.Descripcion.Contains(buscar_Activo));
            }

            return View(await Activos.ToListAsync());
        }

        // GET: ActivoFijos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ActivosFijos == null)
            {
                return NotFound();
            }

            var activoFijo = await _context.ActivosFijos
                .Include(a => a.Departamento)
                .Include(a => a.TipoActivo)
                .FirstOrDefaultAsync(m => m.Id_activo_fijo == id);
            if (activoFijo == null)
            {
                return NotFound();
            }

            return View(activoFijo);
        }

        // GET: ActivoFijos/Create
        public IActionResult Create()
        {
            ViewData["Id_departamento"] = new SelectList(_context.departamentos, "Id_departamento", "Descripcion");
            ViewData["Id_tipo_activo"] = new SelectList(_context.TipoActivos, "Id_tipo_activo", "Descripcion");
            return View();
        }

        // POST: ActivoFijos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_activo_fijo,Descripcion,Id_departamento,Id_tipo_activo,FechaRegistro,ValorCompra,DepreciacionAcumulada,Estado")] ActivoFijo activoFijo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(activoFijo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_departamento"] = new SelectList(_context.departamentos, "Id_departamento", "Descripcion", activoFijo.Id_departamento);
            ViewData["Id_tipo_activo"] = new SelectList(_context.TipoActivos, "Id_tipo_activo", "Descripcion", activoFijo.Id_tipo_activo);
            return View(activoFijo);
        }

        // GET: ActivoFijos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ActivosFijos == null)
            {
                return NotFound();
            }

            var activoFijo = await _context.ActivosFijos.FindAsync(id);
            if (activoFijo == null)
            {
                return NotFound();
            }
            ViewData["Id_departamento"] = new SelectList(_context.departamentos, "Id_departamento", "Descripcion", activoFijo.Id_departamento);
            ViewData["Id_tipo_activo"] = new SelectList(_context.TipoActivos, "Id_tipo_activo", "Descripcion", activoFijo.Id_tipo_activo);
            return View(activoFijo);
        }

        // POST: ActivoFijos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_activo_fijo,Descripcion,Id_departamento,Id_tipo_activo,FechaRegistro,ValorCompra,DepreciacionAcumulada,Estado")] ActivoFijo activoFijo)
        {
            if (id != activoFijo.Id_activo_fijo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activoFijo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivoFijoExists(activoFijo.Id_activo_fijo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_departamento"] = new SelectList(_context.departamentos, "Id_departamento", "Descripcion", activoFijo.Id_departamento);
            ViewData["Id_tipo_activo"] = new SelectList(_context.TipoActivos, "Id_tipo_activo", "Descripcion", activoFijo.Id_tipo_activo);
            return View(activoFijo);
        }

        // GET: ActivoFijos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ActivosFijos == null)
            {
                return NotFound();
            }

            var activoFijo = await _context.ActivosFijos
                .Include(a => a.Departamento)
                .Include(a => a.TipoActivo)
                .FirstOrDefaultAsync(m => m.Id_activo_fijo == id);
            if (activoFijo == null)
            {
                return NotFound();
            }

            return View(activoFijo);
        }

        // POST: ActivoFijos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ActivosFijos == null)
            {
                return Problem("Entity set 'MyDbContext.ActivosFijos'  is null.");
            }
            var activoFijo = await _context.ActivosFijos.FindAsync(id);
            if (activoFijo != null)
            {
                _context.ActivosFijos.Remove(activoFijo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActivoFijoExists(int id)
        {
          return (_context.ActivosFijos?.Any(e => e.Id_activo_fijo == id)).GetValueOrDefault();
        }
    }
}

Views/ActivoFijos/Create.cshtml
@model activos.Models.ActivoFijo

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Activo Fijo</h1>

<h4 class="text-center">Activo Fijo</h4>
<hr />
<div class="row justify-content-center my-5">
    <div class="col-lg-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" placeholder="Nombre del Activo Fijo" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id_departamento" class="control-label"></label>
                <select asp-for="Id_departamento" class ="form-control" asp-items="ViewBag.Id_departamento"></select>
            </div>
            <div class="form-group">
                <label asp-for="Id_tipo_activo" class="control-label"></label>
                <select asp-for="Id_tipo_activo" class ="form-control" asp-items="ViewBag.Id_tipo_activo"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorCompra" class="control-label"></label>
                <input asp-for="ValorCompra" class="form-control" placeholder="Inserta el Valor de Compra" />
                <span asp-validation-for="ValorCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepreciacionAcumulada" class="control-label"></label>
                <input asp-for="DepreciacionAcumulada" class="form-control" placeholder="Inserta la Depreciacion" />
                <span asp-validation-for="DepreciacionAcumulada" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ActivoFijos/Delete.cshtml
@model activos.Models.ActivoFijo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ActivoFijo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoActivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoActivo.CuentaContableCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepreciacionAcumulada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepreciacionAcumulada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id_activo_fijo" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Volver</a>
    </form>
</div>

Views/ActivoFijos/Details.cshtml
@model activos.Models.ActivoFijo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ActivoFijo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoActivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoActivo.CuentaContableCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DepreciacionAcumulada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DepreciacionAcumulada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id_activo_fijo" class="btn btn-warning">Editar Activos Fijos</a> |
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>

Views/ActivoFijos/Edit.cshtml
@model activos.Models.ActivoFijo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ActivoFijo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id_activo_fijo" />
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id_departamento" class="control-label"></label>
                <select asp-for="Id_departamento" class="form-control" asp-items="ViewBag.Id_departamento"></select>
                <span asp-validation-for="Id_departamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id_tipo_activo" class="control-label"></label>
                <select asp-for="Id_tipo_activo" class="form-control" asp-items="ViewBag.Id_tipo_activo"></select>
                <span asp-validation-for="Id_tipo_activo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorCompra" class="control-label"></label>
                <input asp-for="ValorCompra" class="form-control" />
                <span asp-validation-for="ValorCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepreciacionAcumulada" class="control-label"></label>
                <input asp-for="DepreciacionAcumulada" class="form-control" />
                <span asp-validation-for="DepreciacionAcumulada" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ActivoFijos/Index.cshtml
@model IEnumerable<activos.Models.ActivoFijo>

@{
    ViewData["Title"] = "Index";
}

<h1>Gestor de Activos Fijos</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Crear un nuevo Activo Fijo</a>
</p>

<form asp-controller="ActivoFijos" asp-action="Index">
    <p>
        Buscar: <input type="text" name="buscar_Activo" class="form-text" />
        <input type="submit" value="Buscar" class="btn-sm btn-dark" />
    </p>
</form>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoActivo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaRegistro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorCompra)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepreciacionAcumulada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento.Descripcion)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.TipoActivo.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaRegistro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorCompra)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepreciacionAcumulada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
                <td class="d-flex justify-content-end">
                    <a asp-action="Edit" asp-route-id="@item.Id_activo_fijo" class="btn btn-warning">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id_activo_fijo" class="btn btn-info">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id_activo_fijo" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>