Models/TipoActivo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace activos.Models
{
    public class TipoActivo
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id_tipo_activo { get; set; }

        [Required]
        [StringLength(100)]
        public string? Descripcion { get; set; }

        [Required(ErrorMessage = "El campo Cuenta Contable Compra es requerido")]
        [StringLength(50)]
        public string? CuentaContableCompra { get; set; }

        [Required(ErrorMessage = "El campo Cuenta Contable Depreciacion es requerido")]
        [StringLength(50)]
        public string? CuentaContableDepreciacion { get; set; }

        public bool Estado { get; set; }

        // Propiedad de navegación para activos fijos
        public ICollection<ActivoFijo>? ActivosFijos { get; set; }
    }
}

Controllers/TipoActivosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using activos.Models;

namespace activos.Controllers
{
    public class TipoActivosController : Controller
    {
        private readonly MyDbContext _context;

        public TipoActivosController(MyDbContext context)
        {
            _context = context;
        }

        // GET: TipoActivos
        public async Task<IActionResult> Index( string buscar_tipo)
        {
            var tipoActivos = from  TipoActivo in _context.TipoActivos select TipoActivo;
            if (!String.IsNullOrEmpty(buscar_tipo))
            {
                tipoActivos = tipoActivos.Where(s => s.Descripcion.Contains(buscar_tipo));
            }

            return View(await tipoActivos.ToListAsync());
        }

        // GET: TipoActivos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TipoActivos == null)
            {
                return NotFound();
            }

            var tipoActivo = await _context.TipoActivos
                .FirstOrDefaultAsync(m => m.Id_tipo_activo == id);
            if (tipoActivo == null)
            {
                return NotFound();
            }

            return View(tipoActivo);
        }

        // GET: TipoActivos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoActivos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_tipo_activo,Descripcion,CuentaContableCompra,CuentaContableDepreciacion,Estado")] TipoActivo tipoActivo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoActivo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoActivo);
        }

        // GET: TipoActivos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TipoActivos == null)
            {
                return NotFound();
            }

            var tipoActivo = await _context.TipoActivos.FindAsync(id);
            if (tipoActivo == null)
            {
                return NotFound();
            }
            return View(tipoActivo);
        }

        // POST: TipoActivos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_tipo_activo,Descripcion,CuentaContableCompra,CuentaContableDepreciacion,Estado")] TipoActivo tipoActivo)
        {
            if (id != tipoActivo.Id_tipo_activo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoActivo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoActivoExists(tipoActivo.Id_tipo_activo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoActivo);
        }

        // GET: TipoActivos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TipoActivos == null)
            {
                return NotFound();
            }

            var tipoActivo = await _context.TipoActivos
                .FirstOrDefaultAsync(m => m.Id_tipo_activo == id);
            if (tipoActivo == null)
            {
                return NotFound();
            }

            return View(tipoActivo);
        }

        // POST: TipoActivos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TipoActivos == null)
            {
                return Problem("Entity set 'MyDbContext.TipoActivos'  is null.");
            }
            var tipoActivo = await _context.TipoActivos.FindAsync(id);
            if (tipoActivo != null)
            {
                _context.TipoActivos.Remove(tipoActivo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoActivoExists(int id)
        {
          return (_context.TipoActivos?.Any(e => e.Id_tipo_activo == id)).GetValueOrDefault();
        }
    }
}

Views/TipoActivos/Create.cshtml
@model activos.Models.TipoActivo

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Tipo de Activos</h1>

<h4 class="text-center">Tipo de Activo</h4>
<hr />
<div class="row justify-content-center my-5">
    <div class="col-lg-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" placeholder="Inserta el Tipo de Activo"/>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuentaContableCompra" class="control-label"></label>
                <input asp-for="CuentaContableCompra" class="form-control" placeholder="Inserta la Cuenta Contable de Compra"/>
                <span asp-validation-for="CuentaContableCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuentaContableDepreciacion" class="control-label"></label>
                <input asp-for="CuentaContableDepreciacion" class="form-control" placeholder="Inserta la Cuenta Contable de Depreciacion"/>
                <span asp-validation-for="CuentaContableDepreciacion" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TipoActivos/Delete.cshtml
@model activos.Models.TipoActivo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TipoActivo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CuentaContableCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CuentaContableCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CuentaContableDepreciacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CuentaContableDepreciacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id_tipo_activo" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Volver</a>
    </form>
</div>

Views/TipoActivos/Details.cshtml
@model activos.Models.TipoActivo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TipoActivo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CuentaContableCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CuentaContableCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CuentaContableDepreciacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CuentaContableDepreciacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id_tipo_activo" class="btn btn-warning">Editar tipo de activo</a> |
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>

Views/TipoActivos/Edit.cshtml
@model activos.Models.TipoActivo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TipoActivo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id_tipo_activo" />
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuentaContableCompra" class="control-label"></label>
                <input asp-for="CuentaContableCompra" class="form-control" />
                <span asp-validation-for="CuentaContableCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuentaContableDepreciacion" class="control-label"></label>
                <input asp-for="CuentaContableDepreciacion" class="form-control" />
                <span asp-validation-for="CuentaContableDepreciacion" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TipoActivos/Index.cshtml
@model IEnumerable<activos.Models.TipoActivo>

@{
    ViewData["Title"] = "Index";
}

<h1>Gestor de Tipos de Activos</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Crear un nuevo tipo de activo</a>
</p>

<form asp-controller="TipoActivos" asp-action="Index">
    <p>
        Buscar: <input type="text" name="buscar_tipo" class="form-text" />
        <input type="submit" value="Buscar" class="btn-sm btn-dark" />
    </p>
</form>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CuentaContableCompra)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CuentaContableDepreciacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th >Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CuentaContableCompra)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CuentaContableDepreciacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
                <td class="d-flex justify-content-end">
                    <a asp-action="Edit" asp-route-id="@item.Id_tipo_activo" class="btn btn-warning">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id_tipo_activo" class="btn btn-info">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id_tipo_activo" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>