Models/Departamentos.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace activos.Models
{
    public class Departamento
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id_departamento { get; set; }

        [Required]
        [StringLength(50)]
        public string? Descripcion { get; set; }

        public bool Estado { get; set; }
    }
}

Controllers/DepartamentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using activos.Models;

namespace activos.Controllers
{
    public class DepartamentosController : Controller
    {
        private readonly MyDbContext _context;

        public DepartamentosController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Departamentos
        public async Task<IActionResult> Index( string buscar_departamento)
        {
            var departamentos = from Departamentos in _context.departamentos select Departamentos;
            if (!String.IsNullOrEmpty(buscar_departamento))
            {
                departamentos= departamentos.Where(s=>s.Descripcion!.Contains(buscar_departamento));
            }

            return View(await departamentos.ToListAsync());
                          
        }

        // GET: Departamentos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.departamentos == null)
            {
                return NotFound();
            }

            var departamento = await _context.departamentos
                .FirstOrDefaultAsync(m => m.Id_departamento == id);
            if (departamento == null)
            {
                return NotFound();
            }

            return View(departamento);
        }

        // GET: Departamentos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departamentos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_departamento,Descripcion,Estado")] Departamento departamento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(departamento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(departamento);
        }

        // GET: Departamentos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.departamentos == null)
            {
                return NotFound();
            }

            var departamento = await _context.departamentos.FindAsync(id);
            if (departamento == null)
            {
                return NotFound();
            }
            return View(departamento);
        }

        // POST: Departamentos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_departamento,Descripcion,Estado")] Departamento departamento)
        {
            if (id != departamento.Id_departamento)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(departamento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartamentoExists(departamento.Id_departamento))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(departamento);
        }

        // GET: Departamentos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.departamentos == null)
            {
                return NotFound();
            }

            var departamento = await _context.departamentos
                .FirstOrDefaultAsync(m => m.Id_departamento == id);
            if (departamento == null)
            {
                return NotFound();
            }

            return View(departamento);
        }

        // POST: Departamentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.departamentos == null)
            {
                return Problem("Entity set 'MyDbContext.departamentos'  is null.");
            }
            var departamento = await _context.departamentos.FindAsync(id);
            if (departamento != null)
            {
                _context.departamentos.Remove(departamento);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartamentoExists(int id)
        {
          return (_context.departamentos?.Any(e => e.Id_departamento == id)).GetValueOrDefault();
        }
    }
}

Views/Departamentos/Create.cshtml
@model activos.Models.Departamento

@{
    ViewData["Title"] = "Create";
}

 <h1>Crear departamento</h1>
<h4 class="text-center">Departamento</h4>

<hr />
<div class="row justify-content-center my-5">

    <div class="col-lg-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" placeholder="Inserte el nombre del departamento" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <a asp-action="Index" class="btn btn-secondary">Volver</a>
    </div>
</div> 

 
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Departamentos/Delete.cshtml
@model activos.Models.Departamento

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar departamento</h1>

<h3>¿Estas seguro de eliminar este departamento?</h3>
<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id_departamento" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Volver</a>
    </form>
</div>

Views/Departamentos/Details.cshtml
@model activos.Models.Departamento

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles del departamento</h1>

<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id_departamento" class="btn btn-warning">Editar departamento</a> |
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>

Views/Departamentos/Edit.cshtml
@model activos.Models.Departamento

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar departamento</h1>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id_departamento" />
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" placeholder="Inserte el nombre del departamento" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar cambios" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Departamentos/Index.cshtml
@model IEnumerable<activos.Models.Departamento>

@{
    ViewData["Title"] = "Departamento";
}

<h1>Gestor de Departamentos</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">Crear un nuevo Departamento</a>
</p>

<form asp-controller="Departamentos" asp-action="Index">
    <p>
        Buscar: <input type="text" name="buscar_departamento" class="form-text" />
        <input type="submit" value="Buscar" class="btn-sm btn-dark" />
    </p>
</form>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
                <td class="d-flex justify-content-end">
                <a asp-action="Edit" asp-route-id="@item.Id_departamento" class="btn btn-warning">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id_departamento" class="btn btn-info">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id_departamento" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>